version: "1.0"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist
    ports:
      - 3000:3000
    container_name: frontend
